name: Mettre à jour le RSS

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  push:
    branches:
      - github-pages

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://www.developpez.com/index/rss
          readme-section: feed
          branch: github-pages
          commit-message: "Mise à jour du RSS"
          max: 6
          path: /content/post/flux_rss.md
